//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIEN
    {
        public Nullable<int> IDOBJET1 { get; set; }
        public Nullable<int> IDOBJET2 { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public Nullable<System.DateTime> DATE_SUPPRESSION { get; set; }
        public string COMMENTAIRE { get; set; }
        public int IDLIEN { get; set; }
    
        public virtual OBJET OBJET { get; set; }
        public virtual OBJET OBJET1 { get; set; }
    }
}
