//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBJET()
        {
            this.LIENs = new HashSet<LIEN>();
            this.LIENs1 = new HashSet<LIEN>();
            this.ELEMENTs = new HashSet<ELEMENT>();
        }
    
        public int IDOBJET { get; set; }
        public Nullable<int> IDTYPEOBJET { get; set; }
        public string NOM { get; set; }
    
        public virtual TYPEOBJET TYPEOBJET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIEN> LIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIEN> LIENs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELEMENT> ELEMENTs { get; set; }
    }
}
