//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUTODONE
    {
        public int IDTUTODONE { get; set; }
        public int IDTUTO { get; set; }
        public int IDUSER { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
    
        public virtual TUTO TUTO { get; set; }
        public virtual USER USER { get; set; }
    }
}
