//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VUE()
        {
            this.ELEMENTs = new HashSet<ELEMENT>();
        }
    
        public int IDVUE { get; set; }
        public string LIBELLE { get; set; }
        public int USER_CREE { get; set; }
        public System.DateTime DATE_CREE { get; set; }
        public Nullable<int> MAINCONTAINERX { get; set; }
        public Nullable<int> MAINCONTAINERY { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELEMENT> ELEMENTs { get; set; }
    }
}
