CREATE TABLE [dbo].[OBJET] (
    [IDOBJET]     INT            IDENTITY (1, 1) NOT NULL,
    [IDTYPEOBJET] INT            NULL,
    [NOM]         NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([IDOBJET] ASC),
    CONSTRAINT [FK_OBJET_TYPEOBJET] FOREIGN KEY ([IDTYPEOBJET]) REFERENCES [dbo].[TYPEOBJET] ([IDTYPEOBJET])
);

