CREATE TABLE [dbo].[TUTOSTEP] (
    [IDTUTOSTEP]      INT            IDENTITY (1, 1) NOT NULL,
    [IDTUTO]          INT            NOT NULL,
    [INDICATION]      NVARCHAR (MAX) NOT NULL,
    [ORDRE]           INT            NOT NULL,
    [IDEVENTTOLISTEN] NVARCHAR (50)  NULL,
    [JSFONCTION]      NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_TUTOSTEP] PRIMARY KEY CLUSTERED ([IDTUTOSTEP] ASC),
    CONSTRAINT [FK_TUTOSTEP_TUTOSTEP] FOREIGN KEY ([IDTUTO]) REFERENCES [dbo].[TUTO] ([IDTUTO])
);

