CREATE TABLE [dbo].[TYPEOBJET] (
    [IDTYPEOBJET] INT            IDENTITY (4, 1) NOT NULL,
    [LIBELLE]     NVARCHAR (MAX) NULL,
    [FAVORISMENU] NCHAR (10)     NULL,
    [ICONE]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_TYPEOBJET] PRIMARY KEY CLUSTERED ([IDTYPEOBJET] ASC)
);

