CREATE TABLE [dbo].[USER] (
    [IDUSER]     INT            IDENTITY (1, 1) NOT NULL,
    [NOM]        NVARCHAR (50)  NOT NULL,
    [MOTDEPASSE] NVARCHAR (MAX) NOT NULL,
    [USER_CREE]  INT            NOT NULL,
    [DATE_CREE]  DATETIME       NOT NULL,
    CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED ([IDUSER] ASC),
    CONSTRAINT [FK_USER_USER] FOREIGN KEY ([USER_CREE]) REFERENCES [dbo].[USER] ([IDUSER])
);

