CREATE TABLE [dbo].[VUE] (
    [IDVUE]          INT            IDENTITY (1, 1) NOT NULL,
    [LIBELLE]        NVARCHAR (MAX) NOT NULL,
    [USER_CREE]      INT            NOT NULL,
    [DATE_CREE]      DATETIME       NOT NULL,
    [MAINCONTAINERX] INT            NULL,
    [MAINCONTAINERY] INT            NULL,
    CONSTRAINT [PK_VUE] PRIMARY KEY CLUSTERED ([IDVUE] ASC),
    CONSTRAINT [FK_VUE_USER] FOREIGN KEY ([USER_CREE]) REFERENCES [dbo].[USER] ([IDUSER])
);

